### ISSUE TITLE
theme

### ISSUE THREAD

**Issue by insxa** [HighMark-31/fossbilling-theme-modern#1]
Hello in your current theme doesnt work language selector, logo is only text, ordering page not working

**Comment by HighMark-31** [comment]
Hi sir,
I will soon check the bugs you found and relaunch the version with the appropriate fixes.

**Comment by insxa** [comment]
Also after login, i get api error

**Comment by HighMark-31** [comment]
I have fixed your issue with the update 1.1

If you find any new errors or suggestion feel free to open another issue

**Comment by insxa** [comment]
order still doesnt work, at least for me, you can check my [website](https://billing.duohost.net/)
login still shows me error
Logo image should be without text if set image
There is lot of errors i get:
ticket view / twig error
invoice error / long numbers
profile -> api key -> generate new key / page doesnt exist (also any page on profile save cant be found)
balance -> add funds i get api page
api keys page not found

**Comment by HighMark-31** [comment]
Hi,
thanks for the update.

The order page issue is already listed as a known bug, and it will be addressed in an upcoming update.

Regarding the other problems you mentioned: those pages are part of additional FOSSBilling modules, not the core system. They still need to be fully implemented and will be added gradually with the next releases.

Thanks for your patience and for reporting your findings.

**Comment by HighMark-31** [comment]
I close this issue, follow the repository, when i publish the 1.2 let me know if is all ok
